version: "3.8"
services: 
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports: 
      - '90:4000'
    networks:
      - mybirdge 
    volumes: 
      # ya ni ra %cd% ni use grna sakxa for windows
      # for mac and linux use $(pwd)
      - C:\Users\jacob\dockerwithmongo:/app 
    depends_on: 
      - mongo    
     
  mongo:
    container_name: mongo
    image: mongo
    ports: 
      - '27017:27017'
    networks:
      - mybirdge  
  
networks: 
  mybirdge:
    driver: bridge



