version: "3.8"
services:
    app:
      container_name: node-prod
      restart: always
      build: 
        context: .
    #   ports: 
    #     - '90:3000'
      environment: 
        - NODE_ENV = production
        # - PORT: 3000 
      command: npm start
