version: "3.8"
services: 
  app:
    container_name: docker-node-mongo
    restart: always
    build: 
      context: .
      args: 
        NODE_ENV : production
      # dockerfile ma rakheko env lai kasari use garne aayena my lord
      # args:
      #   - GIT_TOKEN=$GIT_TOKEN
      #   - DB_PWD=$DB_PWD
    ports: 
      - '90:${PORT}'
    networks:
      - mybirdge 
    volumes: 
      # ya ni ra %cd% ni use grna sakxa for windows
      # for mac and linux use $(pwd)
      # here ro after app specify container is only allowed to read so that from the conatiner we cant create or cahnge file and its content
      - C:\Users\jacob\dockerwithmongo:/app:ro 
      #  this is anonymous volum which persist only on conatiner and gets deleted when container is removed
      - /app/node_modules  
    depends_on: 
      - mongo
    environment: 
      #  ya nira portspecify grda dockerfile ma env ko through set ko PORT overrride hunxa
      PORT : ${PORT}    
     
  mongo:
    container_name: mongo
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    #  ya nira siddhai MONGO_IP: mongo esari data patahye ni huna or ${} ko se garera variable pass grna ni paiyo
      # MONGO_IP: ${MONGO_IP}
      # MONGO_PORT: ${MONGO_PORT}
      # MONGO_USER: ${MONGO_USER}
      # MONGO_PASSWORD: ${MONGO_PASSWORD}
      

    image: mongo
    ports: 
      - '27017:27017'
    networks:
      - mybirdge  
    volumes: 
      - mongo-db:/data/db  
  
networks: 
  mybirdge:
    driver: bridge

volumes:
  mongo-db:    



